apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-monitor
  namespace: sre-monitoring
  labels:
    release: sre-stack # This label MUST match your Helm install
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
      - ingress-nginx # Adjust if your ingress runs in a different namespace
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics